name: Build Plugins

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build all plugins
        run: ./gradlew build --no-daemon

      - name: Find all built .cs3 plugins
        id: find_plugins
        run: |
          find . -name "*.cs3" > cs3_list.txt
          echo "CS3_LIST<<EOF" >> $GITHUB_ENV
          cat cs3_list.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload all plugin .cs3 files
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: |
            **/*.cs3
