name: Build Cloudstream Plugin

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew :hh3dtq3Provider:assembleRelease

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: hh3dtq3Provider-plugin
          path: hh3dtq3Provider/build/outputs/plugin/*.cs3

      - name: Release plugin on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: hh3dtq3Provider/build/outputs/plugin/*.cs3
          tag: nightly
          allowUpdates: true
          generateReleaseNotes: true
