name: Build Cloudstream Plugin

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew :hh3dtq3Provider:assembleRelease

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: hh3dtq3Provider-plugin
          path: hh3dtq3Provider/build/outputs/plugin/*.cs3
